name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, "pypy-3.8"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install bitstring>=3.1.3
        pip install pyflakes
        pip install pytest
        pip install pybufrkit
        pip install six

    - name: Run tests
      run: |
        pytest || true
        pyflakes pybufrkit tests || true
