name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        include:
          - python-version: 3.8
            allow_failure: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pipenv run pip install six==1.16.0  # Update to a compatible version of six
        pipenv run pip install urllib3==1.26.5  # Update to a compatible version of urllib3

    - name: Lint
      run: pipenv run lint

    - name: Test
      run: pipenv run test
